database:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "cxz"
  name: "face"

redis:
  host: "192.168.24.101"
  port: 6379
  password: "cxz247339"
  db: 0
  pool_size: 10            # 连接池大小，默认为 10
  min_idle_conns: 3        # 最小空闲连接数，默认为 3
  dial_timeout: 5s        # 连接超时时间
  read_timeout: 30s       # 读取超时时间
  write_timeout: 30s      # 写入超时时间
  idle_timeout: 300s      # 连接最大空闲时间，默认为 5分钟（300秒）
  max_retries: 3         # 最大重试次数

app:
  host: ""
  port: 8081
  domain: "127.0.0.1"

# 日志配置
log:
  #  level: "debug"
  logPath: "./logs"
  appName: "face"
